### ISSUE TITLE
 error: unresolved import `std::os::macos::fs::MetadataExt`. Could not find `macos` in `std::os

### ISSUE THREAD

**Issue by Matvey-Kuk** [alexcrichton/filetime#1]
Hello!
I'm trying Iron Framework and have such error during compiling it's https://github.com/iron/staticfile.git middleware. There is filetime 0.1.2 dependence and as I see, main reason is in this library.

Os: Mac Os X 10.10.3

Error log from cargo:

/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.2/src/lib.rs:83:29: 83:57 error: unresolved import `std::os::macos::fs::MetadataExt`. Could not find `macos` in `std::os`
/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.2/src/lib.rs:83                         use std::os::$i::fs::MetadataExt;
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.2/src/lib.rs:77:9: 96:10 note: in expansion of birthtim!
/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.2/src/lib.rs:98:9: 104:10 note: expansion site
error: aborting due to previous error

Thank you!

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately this library currently only compiles on the nightly channel of Rust due to its usage of unstable features. These features will soon make their way into beta, however, and they're likely to be stable for 1.1, so this shouldn't be required for too long!

**Comment by Matvey-Kuk** [comment]
@alexcrichton , thank you!

curl https://static.rust-lang.org/rustup.sh > rustup.sh;
rustup.sh --channel=nightly;

Helped =)

**Comment by AutomatedTester** [comment]
Is this still a feature requiring Rust nightly?

**Comment by alexcrichton** [comment]
As of 1.1 this library should work on stable (it just doesn't work on 1.0)
